apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`api.my-domain.com`) && PathPrefix(`/users`)
      kind: Rule
      priority: 2000
      services:
        - name: new-api
          port: 80
